Feat/component/header
tech-university-india/staffing-pipeline-frontend pull request #11
Opened 2023-03-04 18:29 UTC by Cosmoboi-i

Created header component with hover css.
Will add button functionality after the structure is approved.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/78909536/222922739-25559f94-44e6-48a9-976d-3f0fab80ba7d.png">

2023-03-05 04:53 UTC, rohini-senthil commented
There is also a header with no tabs. Can we have a boolean attribute to control this?

<img width="563" alt="image" src="https://user-images.githubusercontent.com/77390012/222942325-2ec07811-6f7f-42a0-b557-2f0908494bd5.png">

2023-03-05 04:54 UTC, rohini-senthil commented
The logo needs to be in the corner by the way

2023-03-05 05:06 UTC, Chetan-MckinseyBEBR commented on src/components/header/header.css
> +
Plz remove empty lines

2023-03-05 05:07 UTC, Chetan-MckinseyBEBR commented on src/components/header/header.css
> +  width: 63vw;
reason for using vw?

2023-03-05 05:32 UTC, Cosmoboi-i commented on src/components/header/header.css
> +  width: 63vw;
The content region will always be a certain ratio of the viewport. We won't be using this in any element with width less that of the whole viewport. But if it's a convention to use percentage, I'll change it.

2023-03-05 05:47 UTC, Cosmoboi-i commented on src/components/header/header.css
> +
1. Added boolean to control navbar
2. removed empty lines
3. I am using gotskills website as a reference. It has the logo fairly in the middle. Have a look at this.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/78909536/222943824-4f207871-616d-4956-afc9-43cfd62e2e7b.png">
If the logo still needs to be in the corner, I'll do that.

2023-03-05 05:52 UTC, Chetan-MckinseyBEBR reviewed
- The css styles are not responsive to support tabs.
- See if u can use tailwind grids

2023-03-06 12:34 UTC, Chetan-MckinseyBEBR requested changes
Add few comments

2023-03-06 12:34 UTC, Chetan-MckinseyBEBR commented on src/components/header/__tests__/index.test.jsx
> +  it('should render correctly without a navbar when Navbar boolean is false', () => {
Add a new line

2023-03-06 12:34 UTC, Chetan-MckinseyBEBR commented on src/components/header/index.jsx
> +            <button className="text-[white] hover:text-[#00A9F4] hover:border-b-[5px] hover:border-b-[#00A9F4] hover:border-solid pt-0 pb-[15px] hover:pb-2.5 px-[5px]">
create a central css color variable in assets rather than having the hex code in here

2023-03-06 15:06 UTC, Cosmoboi-i commented on src/components/header/index.jsx
> +            <button className="text-[white] hover:text-[#00A9F4] hover:border-b-[5px] hover:border-b-[#00A9F4] hover:border-solid pt-0 pb-[15px] hover:pb-2.5 px-[5px]">
Done

2023-03-07 03:53 UTC, Chetan-MckinseyBEBR requested changes
Added one comment. Good to merge after this change

2023-03-07 03:53 UTC, Chetan-MckinseyBEBR commented on src/components/header/index.jsx
> +export default function Header(props) {
destructure the props

2023-03-07 12:36 UTC, Chetan-MckinseyBEBR approved these changes

2023-03-07 12:37 UTC, merged