Feature/input component
tech-university-india/staffing-pipeline-frontend pull request #13
Opened 2023-03-05 06:58 UTC by Promit-revar

Created input component with tests and css

2023-03-05 07:24 UTC, Chetan-MckinseyBEBR commented on src/components/InputComponent/index.jsx
> +export default function InputComponent(props) {
destructure the props.

2023-03-05 09:19 UTC, Promit-revar commented
<img width="292" alt="Screenshot 2023-03-05 at 2 47 37 PM" src="https://user-images.githubusercontent.com/61512425/222952152-a4cc5421-59c0-4af4-bb87-a7c8fff13135.png">

2023-03-06 12:31 UTC, Chetan-MckinseyBEBR requested changes
Format the code with proper new lines added between code sections

2023-03-06 12:31 UTC, Chetan-MckinseyBEBR commented on src/components/InputComponent/InputComponent.css
> +.search-input{
Add new line

2023-03-06 12:31 UTC, Chetan-MckinseyBEBR commented on src/components/InputComponent/__tests__/index.test.jsx
> +  it('should display placeholder value passed to it', () => {
Add a new line

2023-03-06 12:31 UTC, Chetan-MckinseyBEBR commented on src/components/InputComponent/index.jsx
> +export default function InputComponent({ className, placeholder }) {
New line

2023-03-06 12:31 UTC, Chetan-MckinseyBEBR commented on src/components/InputComponent/index.jsx
> +InputComponent.propTypes = {
New line

2023-03-07 08:44 UTC, Chetan-MckinseyBEBR approved these changes

2023-03-07 12:38 UTC, merged