Feat/component/header: Fix McK logo aspect ratio
tech-university-india/staffing-pipeline-frontend pull request #22
Opened 2023-03-13 10:21 UTC by Cosmoboi-i

2023-03-13 10:25 UTC, Cosmoboi-i commented
<img width="828" alt="image" src="https://user-images.githubusercontent.com/78909536/224674472-3b1fb000-78d5-405d-9b63-81e11564889b.png">
<img width="793" alt="image" src="https://user-images.githubusercontent.com/78909536/224674912-030f8f72-1d7d-4290-96fc-9eb86d09c170.png">
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/78909536/224675001-2578f6e6-1f46-4351-a93b-c14bf08be713.png">

2023-03-13 10:41 UTC, Chetan-MckinseyBEBR approved these changes

2023-03-15 04:39 UTC, Chetan-MckinseyBEBR requested changes
Added few comments

2023-03-15 04:39 UTC, Chetan-MckinseyBEBR commented on src/components/Header/index.jsx
> +                  : 'text-[white] hover:text-cyan hover:border-b-[5px] hover:border-b-cyan hover:border-solid pt-0 pb-[15px] hover:pb-2.5 px-[5px]'
have these class string in a variable and reuse them rather than repeating it

2023-03-15 06:20 UTC, Cosmoboi-i commented on src/components/Header/index.jsx
> +                  : 'text-[white] hover:text-cyan hover:border-b-[5px] hover:border-b-cyan hover:border-solid pt-0 pb-[15px] hover:pb-2.5 px-[5px]'
Done

2023-03-15 07:27 UTC, Chetan-MckinseyBEBR approved these changes

2023-03-15 07:27 UTC, merged