Feature/login page
tech-university-india/staffing-pipeline-frontend pull request #38
Opened 2023-03-14 17:11 UTC by Promit-revar

Login page with functionalities...
![Uploading Screenshot 2023-03-14 at 10.40.48 PM.png…]()

2023-03-15 04:35 UTC, Chetan-MckinseyBEBR requested changes
Added few comments

2023-03-15 04:35 UTC, Chetan-MckinseyBEBR commented on public/index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHE
Use react fontawsome as an npm package in the project rather than CDN

2023-03-15 04:35 UTC, Chetan-MckinseyBEBR commented on src/components/ImageCard/ImageCard.css
Why are ImageCard deleted?

2023-03-15 04:35 UTC, Chetan-MckinseyBEBR commented on src/components/InputComponent/index.jsx
> +      <input type={type} className={'login-input'} placeholder={placeholder} onChange={handleChange} />
Why does the Input component has the login-input class?? That makes this component not generic

2023-03-15 04:35 UTC, Chetan-MckinseyBEBR commented on src/pages/LoginPage/LoginPage.css
> +.error{
empty lines after each code section

2023-03-15 04:35 UTC, Chetan-MckinseyBEBR commented on src/utils/authMakeRequest/index.js
> +  //console.log('requestDetails', requestDetails);
Remove commented code

2023-03-15 04:35 UTC, Chetan-MckinseyBEBR commented on src/utils/makeRequest/index.js
> +import AUTHORIZATION_TOKEN from '../../constants/authorizationToken.js';
Why .js?

2023-03-15 06:15 UTC, Promit-revar commented on src/components/ImageCard/ImageCard.css
One of my teammate told me that we are not using it anymore but I will add it again

2023-03-15 06:31 UTC, Promit-revar commented on src/components/InputComponent/index.jsx
> +      <input type={type} className={'login-input'} placeholder={placeholder} onChange={handleChange} />
its because no where else we are using input component other than login

2023-03-16 06:04 UTC, Promit-revar commented
<img width="1680" alt="Screenshot 2023-03-16 at 11 33 56 AM" src="https://user-images.githubusercontent.com/61512425/225529191-bec11e3e-fd01-4b17-95af-0d1c71fd92fd.png">

2023-03-16 07:47 UTC, Chetan-MckinseyBEBR approved these changes

2023-03-16 07:47 UTC, merged